name: test_work
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # Value equality
  equatable: ^2.0.5
    # network
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.7.0
  # servise locator
  get_it: ^7.2.0
  # WebView for Flutter
  webview_flutter: ^4.0.4
  # code generators
  # freezed
  freezed_annotation: ^2.2.0
  # bloc state managment
  flutter_bloc: ^8.1.1
  # Local cache
  shared_preferences: ^2.0.18
#  Firebase
  firebase_core: ^2.7.0
  firebase_remote_config: ^3.0.2
#  Emulator
  device_info_plus: ^8.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # freezed
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  # code generators
  build_runner: ^2.3.2
  # Functional programming thingies
  dartz: ^0.10.1


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/photo.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
